#!/bin/bash
MOUNTPOINT="$HOME/Desktop/mnt"
REMOTE_FOLDER="/u/cs/ugrad/ari/Classes/"
FLAGS="-o auto_cache,reconnect,defer_permissions,noappledouble,volname=lnxsrv"

source unmount-lnxsrv

printf "\tMounting"
sshfs ucla:$REMOTE_FOLDER $MOUNTPOINT $FLAGS
printf "\tDone!\n"
