#!/bin/bash
MOUNTPOINT="$HOME/Desktop/mnt"
HOST="$1"
REMOTE_FOLDER="$2"
FLAGS="-o auto_cache,reconnect,defer_permissions,noappledouble,volname=lnxsrv"

if [ $HOST = "ucla" ] && ! connected lnxsrv.seas.ucla.edu; then
  echo "Server offline. Are you connected to the VPN?"
elif [ $HOST = bb ] && ! connected 192.168.6.2; then
  echo "BeagleBone offline. Is it plugged in?"
else
  source unmount-myMount
  printf "\tMounting"
  sshfs $HOST:$REMOTE_FOLDER $MOUNTPOINT $FLAGS
  printf "\tDone!\n"
  exit 0
fi

echo "Exiting script"
exit 1
