#!/bin/bash

function isMounted {
  if mount | grep -qs $1; then
    return 0
  else
    return 1
  fi
}


if isMounted ~/Desktop/mnt; then
  printf "lnxsrv was already mounted.\n"
  printf "\tUnmounting"
  umount ~/Desktop/mnt
  printf "\tDone!\n"
fi
